### ISSUE TITLE
Moving bosh-prometheus repos to cloudfoundry-org

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/prometheus-boshrelease#491]
Hi all,

Following the security incident on the cloudfoundry-community, now seems a good time to consider hardening the administrative aspects of the maintenance of the Prometheus-bosh org in order to limit possible supply chain risks, and avoid that multiple members of CF community maintain a private fork/ci for the bosh-prometheus repos. 

The CFF TOC is welcoming proposal to moving community repos to the cloudfoundry org, as discussed into https://github.com/cloudfoundry/community/issues/778

@ArthurHlt @benjaminguttmann-avtq @bkez322 @frodenas @gmllt @mdimiceli @mkuratczyk  do you see any issue with this move ?

I guess the impact for maintainers would be the onboarding process, and possibly changes to CI to secure it.
For contributors, the impact is likely that they'll now need to sign the CFF CLA before getting their PRs merged.

If there is no objections, on monday I'll try open an issue onto https://github.com/cloudfoundry/community/issues/ to start the discussion with CFF TOC

**Comment by benjaminguttmann-avtq** [comment]
@gberche-orange I think we finished this step. Thanks for your work on that.
